// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYF594pSDwb9QO-KyHyeiD2-Q1Y1LEZFE',
    appId: '1:15463448671:web:dcb06708ba7cef88bddbea',
    messagingSenderId: '15463448671',
    projectId: 'csc234-38a37',
    authDomain: 'csc234-38a37.firebaseapp.com',
    storageBucket: 'csc234-38a37.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClTpRiVE1jpXYmdwtjuoo48P9B1PZFB6w',
    appId: '1:15463448671:android:5abf0e5627603686bddbea',
    messagingSenderId: '15463448671',
    projectId: 'csc234-38a37',
    storageBucket: 'csc234-38a37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy1Pfr9Ubw9mRaAwF_aZoWS_TdkVvaVTo',
    appId: '1:15463448671:ios:72235595d5751a74bddbea',
    messagingSenderId: '15463448671',
    projectId: 'csc234-38a37',
    storageBucket: 'csc234-38a37.appspot.com',
    iosClientId: '15463448671-c3gijoogep1bi7og8f40fhfaehvj82vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy1Pfr9Ubw9mRaAwF_aZoWS_TdkVvaVTo',
    appId: '1:15463448671:ios:72235595d5751a74bddbea',
    messagingSenderId: '15463448671',
    projectId: 'csc234-38a37',
    storageBucket: 'csc234-38a37.appspot.com',
    iosClientId: '15463448671-c3gijoogep1bi7og8f40fhfaehvj82vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
